### ISSUE TITLE
在ubuntu上运行报错

### ISSUE THREAD

**Issue by 725216** [Special-Week/singbox_config_generator#1]
@DESKTOP-INDA4NN:~/singbox$ ls
README.md  __main__.py  node.txt  readmeImg
@DESKTOP-INDA4NN:~/singbox$ python __main__.py
  File "__main__.py", line 13
    def decode_vless(node: str) -> Dict:
                         ^
SyntaxError: invalid syntax

**Comment by Special-Week** [comment]
![image](https://github.com/Special-Week/singbox_config_generator/assets/87489040/64bb16fe-8cac-4f00-b38a-b413dc7bf9c3)
不会吧

**Comment by 725216** [comment]
python __main__.py换成python3 __main__.py可以了
